#!/usr/bin/env bash
#pings an IP address passed as an argument


# Check if an argument is provided
if [ $# -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
# Ping the IP 5 times
else
    ping -c 5 "$1"
fi
